plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton
title: Muhamad Haidar Khan
description: Thank You For Visiting! :)
avatar: https://avatars.githubusercontent.com/u/132541949?s=400&u=6d0eea2a6eb3e22420f319d19f9063b81b551e7d&v=4
subscribe: false
location: Lahore, Punjab, Pakistan
author: Haidar
skin: sunrise
social:
  name: Haidar
  links:
    - https://linkedin.com/in/haidarkhan
    - https://github.com/mhaidarkhan
    - https://mhaidarkhan.github.io/assets/resume.pdf
